### PR TITLE
Fix winapi issues from flock() rework

### PR DESCRIPTION
**Pull request by pfmooney**
This should fix the breakage on Windows from #91  

Sorry about the extra hassle.

### CODE REVIEW

**Comment by phil-opp** [comment]
I just merged #93 with the CI setup. Could you rebase on top of the latest master so that the checks are run for this PR?

**Comment by pfmooney** [comment]
Happy to!

**Comment by phil-opp** [comment]
Awesome, thanks!

**Comment by pfmooney** [comment]
Sorry again for the extra round trip.

**Comment by phil-opp** [comment]
Published as v0.6.2.

**Pull request merged**
